package com.vokyo.backend.activity;

public enum ActivityEventType {
    PROJECT_CREATED,
    ISSUE_CREATED,
    COMMENT_CREATED,
    ISSUE_STATUS_CHANGED,
    ISSUE_TITLE_CHANGED,
    ISSUE_PRIORITY_CHANGED,
    ISSUE_ASSIGNEE_CHANGED,
    ISSUE_DUE_DATE_CHANGED
}
